//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleBooks.Codes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OSIS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OSIS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleBooks.Codes.OSIS", typeof(OSIS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acts.
        /// </summary>
        public static string Acts {
            get {
                return ResourceManager.GetString("Acts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amos.
        /// </summary>
        public static string Amos {
            get {
                return ResourceManager.GetString("Amos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Chr.
        /// </summary>
        public static string Chronicles1 {
            get {
                return ResourceManager.GetString("Chronicles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Chr.
        /// </summary>
        public static string Chronicles2 {
            get {
                return ResourceManager.GetString("Chronicles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Col.
        /// </summary>
        public static string Colossians {
            get {
                return ResourceManager.GetString("Colossians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Cor.
        /// </summary>
        public static string Corinthians1 {
            get {
                return ResourceManager.GetString("Corinthians1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Cor.
        /// </summary>
        public static string Corinthians2 {
            get {
                return ResourceManager.GetString("Corinthians2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dan.
        /// </summary>
        public static string Daniel {
            get {
                return ResourceManager.GetString("Daniel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deut.
        /// </summary>
        public static string Deuteronomy {
            get {
                return ResourceManager.GetString("Deuteronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eccl.
        /// </summary>
        public static string Ecclesiastes {
            get {
                return ResourceManager.GetString("Ecclesiastes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eph.
        /// </summary>
        public static string Ephesians {
            get {
                return ResourceManager.GetString("Ephesians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esth.
        /// </summary>
        public static string Esther {
            get {
                return ResourceManager.GetString("Esther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exod.
        /// </summary>
        public static string Exodus {
            get {
                return ResourceManager.GetString("Exodus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezek.
        /// </summary>
        public static string Ezekiel {
            get {
                return ResourceManager.GetString("Ezekiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezra.
        /// </summary>
        public static string Ezra {
            get {
                return ResourceManager.GetString("Ezra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gal.
        /// </summary>
        public static string Galatians {
            get {
                return ResourceManager.GetString("Galatians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen.
        /// </summary>
        public static string Genesis {
            get {
                return ResourceManager.GetString("Genesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hab.
        /// </summary>
        public static string Habakkuk {
            get {
                return ResourceManager.GetString("Habakkuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hag.
        /// </summary>
        public static string Haggai {
            get {
                return ResourceManager.GetString("Haggai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heb.
        /// </summary>
        public static string Hebrews {
            get {
                return ResourceManager.GetString("Hebrews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hos.
        /// </summary>
        public static string Hosea {
            get {
                return ResourceManager.GetString("Hosea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isa.
        /// </summary>
        public static string Isaiah {
            get {
                return ResourceManager.GetString("Isaiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jas.
        /// </summary>
        public static string James {
            get {
                return ResourceManager.GetString("James", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jer.
        /// </summary>
        public static string Jeremiah {
            get {
                return ResourceManager.GetString("Jeremiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joel.
        /// </summary>
        public static string Joel {
            get {
                return ResourceManager.GetString("Joel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John.
        /// </summary>
        public static string John {
            get {
                return ResourceManager.GetString("John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1John.
        /// </summary>
        public static string John1 {
            get {
                return ResourceManager.GetString("John1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2John.
        /// </summary>
        public static string John2 {
            get {
                return ResourceManager.GetString("John2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3John.
        /// </summary>
        public static string John3 {
            get {
                return ResourceManager.GetString("John3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jonah.
        /// </summary>
        public static string Jonah {
            get {
                return ResourceManager.GetString("Jonah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Josh.
        /// </summary>
        public static string Joshua {
            get {
                return ResourceManager.GetString("Joshua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jude.
        /// </summary>
        public static string Jude {
            get {
                return ResourceManager.GetString("Jude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judg.
        /// </summary>
        public static string Judges {
            get {
                return ResourceManager.GetString("Judges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Kgs.
        /// </summary>
        public static string Kings1 {
            get {
                return ResourceManager.GetString("Kings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Kgs.
        /// </summary>
        public static string Kings2 {
            get {
                return ResourceManager.GetString("Kings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lam.
        /// </summary>
        public static string Lamentations {
            get {
                return ResourceManager.GetString("Lamentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lev.
        /// </summary>
        public static string Leviticus {
            get {
                return ResourceManager.GetString("Leviticus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luke.
        /// </summary>
        public static string Luke {
            get {
                return ResourceManager.GetString("Luke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mal.
        /// </summary>
        public static string Malachi {
            get {
                return ResourceManager.GetString("Malachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matt.
        /// </summary>
        public static string Matthew {
            get {
                return ResourceManager.GetString("Matthew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mic.
        /// </summary>
        public static string Micah {
            get {
                return ResourceManager.GetString("Micah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nah.
        /// </summary>
        public static string Nahum {
            get {
                return ResourceManager.GetString("Nahum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neh.
        /// </summary>
        public static string Nehemiah {
            get {
                return ResourceManager.GetString("Nehemiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obad.
        /// </summary>
        public static string Obadiah {
            get {
                return ResourceManager.GetString("Obadiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Pet.
        /// </summary>
        public static string Peter1 {
            get {
                return ResourceManager.GetString("Peter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Pet.
        /// </summary>
        public static string Peter2 {
            get {
                return ResourceManager.GetString("Peter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phlm.
        /// </summary>
        public static string Philemon {
            get {
                return ResourceManager.GetString("Philemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phil.
        /// </summary>
        public static string Philippians {
            get {
                return ResourceManager.GetString("Philippians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prov.
        /// </summary>
        public static string Proverbs {
            get {
                return ResourceManager.GetString("Proverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ps.
        /// </summary>
        public static string Psalms {
            get {
                return ResourceManager.GetString("Psalms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev.
        /// </summary>
        public static string Revelation {
            get {
                return ResourceManager.GetString("Revelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom.
        /// </summary>
        public static string Romans {
            get {
                return ResourceManager.GetString("Romans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruth.
        /// </summary>
        public static string Ruth {
            get {
                return ResourceManager.GetString("Ruth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Sam.
        /// </summary>
        public static string Samuel1 {
            get {
                return ResourceManager.GetString("Samuel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Sam.
        /// </summary>
        public static string Samuel2 {
            get {
                return ResourceManager.GetString("Samuel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string SongOfSongs {
            get {
                return ResourceManager.GetString("SongOfSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Thess.
        /// </summary>
        public static string Thessalonians1 {
            get {
                return ResourceManager.GetString("Thessalonians1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Thess.
        /// </summary>
        public static string Thessalonians2 {
            get {
                return ResourceManager.GetString("Thessalonians2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Tim.
        /// </summary>
        public static string Timothy1 {
            get {
                return ResourceManager.GetString("Timothy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Tim.
        /// </summary>
        public static string Timothy2 {
            get {
                return ResourceManager.GetString("Timothy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titus.
        /// </summary>
        public static string Titus {
            get {
                return ResourceManager.GetString("Titus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zech.
        /// </summary>
        public static string Zechariah {
            get {
                return ResourceManager.GetString("Zechariah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeph.
        /// </summary>
        public static string Zephaniah {
            get {
                return ResourceManager.GetString("Zephaniah", resourceCulture);
            }
        }
    }
}
