//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleBooks.Metadata {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chapters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chapters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleBooks.Metadata.Chapters", typeof(Chapters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string Acts {
            get {
                return ResourceManager.GetString("Acts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Amos {
            get {
                return ResourceManager.GetString("Amos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        public static string Chronicles1 {
            get {
                return ResourceManager.GetString("Chronicles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string Chronicles2 {
            get {
                return ResourceManager.GetString("Chronicles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Colossians {
            get {
                return ResourceManager.GetString("Colossians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string Corinthians1 {
            get {
                return ResourceManager.GetString("Corinthians1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string Corinthians2 {
            get {
                return ResourceManager.GetString("Corinthians2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string Daniel {
            get {
                return ResourceManager.GetString("Daniel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.
        /// </summary>
        public static string Deuteronomy {
            get {
                return ResourceManager.GetString("Deuteronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string Ecclesiastes {
            get {
                return ResourceManager.GetString("Ecclesiastes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Ephesians {
            get {
                return ResourceManager.GetString("Ephesians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Esther {
            get {
                return ResourceManager.GetString("Esther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        public static string Exodus {
            get {
                return ResourceManager.GetString("Exodus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        public static string Ezekiel {
            get {
                return ResourceManager.GetString("Ezekiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Ezra {
            get {
                return ResourceManager.GetString("Ezra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Galatians {
            get {
                return ResourceManager.GetString("Galatians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string Genesis {
            get {
                return ResourceManager.GetString("Genesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Habakkuk {
            get {
                return ResourceManager.GetString("Habakkuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Haggai {
            get {
                return ResourceManager.GetString("Haggai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string Hebrews {
            get {
                return ResourceManager.GetString("Hebrews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string Hosea {
            get {
                return ResourceManager.GetString("Hosea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66.
        /// </summary>
        public static string Isaiah {
            get {
                return ResourceManager.GetString("Isaiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string James {
            get {
                return ResourceManager.GetString("James", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52.
        /// </summary>
        public static string Jeremiah {
            get {
                return ResourceManager.GetString("Jeremiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Joel {
            get {
                return ResourceManager.GetString("Joel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string John {
            get {
                return ResourceManager.GetString("John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string John1 {
            get {
                return ResourceManager.GetString("John1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string John2 {
            get {
                return ResourceManager.GetString("John2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string John3 {
            get {
                return ResourceManager.GetString("John3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Jonah {
            get {
                return ResourceManager.GetString("Jonah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string Joshua {
            get {
                return ResourceManager.GetString("Joshua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Jude {
            get {
                return ResourceManager.GetString("Jude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string Judges {
            get {
                return ResourceManager.GetString("Judges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string Kings1 {
            get {
                return ResourceManager.GetString("Kings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string Kings2 {
            get {
                return ResourceManager.GetString("Kings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Lamentations {
            get {
                return ResourceManager.GetString("Lamentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        public static string Leviticus {
            get {
                return ResourceManager.GetString("Leviticus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string Luke {
            get {
                return ResourceManager.GetString("Luke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Malachi {
            get {
                return ResourceManager.GetString("Malachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        public static string Matthew {
            get {
                return ResourceManager.GetString("Matthew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string Micah {
            get {
                return ResourceManager.GetString("Micah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Nahum {
            get {
                return ResourceManager.GetString("Nahum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string Nehemiah {
            get {
                return ResourceManager.GetString("Nehemiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Obadiah {
            get {
                return ResourceManager.GetString("Obadiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Peter1 {
            get {
                return ResourceManager.GetString("Peter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Peter2 {
            get {
                return ResourceManager.GetString("Peter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Philemon {
            get {
                return ResourceManager.GetString("Philemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Philippians {
            get {
                return ResourceManager.GetString("Philippians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string Proverbs {
            get {
                return ResourceManager.GetString("Proverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string Psalms {
            get {
                return ResourceManager.GetString("Psalms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string Revelation {
            get {
                return ResourceManager.GetString("Revelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string Romans {
            get {
                return ResourceManager.GetString("Romans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Ruth {
            get {
                return ResourceManager.GetString("Ruth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string Samuel1 {
            get {
                return ResourceManager.GetString("Samuel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string Samuel2 {
            get {
                return ResourceManager.GetString("Samuel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string SongOfSongs {
            get {
                return ResourceManager.GetString("SongOfSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Thessalonians1 {
            get {
                return ResourceManager.GetString("Thessalonians1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Thessalonians2 {
            get {
                return ResourceManager.GetString("Thessalonians2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Timothy1 {
            get {
                return ResourceManager.GetString("Timothy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Timothy2 {
            get {
                return ResourceManager.GetString("Timothy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Titus {
            get {
                return ResourceManager.GetString("Titus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string Zechariah {
            get {
                return ResourceManager.GetString("Zechariah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Zephaniah {
            get {
                return ResourceManager.GetString("Zephaniah", resourceCulture);
            }
        }
    }
}
